WebApplication43/Controllers/AnasayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication43.Models;
using PagedList;
using PagedList.Mvc;

namespace WebApplication43.Controllers
{
    public class AnasayfaController : Controller
    {
        kitapciEntities db = new kitapciEntities();
        // GET: Anasayfa
        public ActionResult Index(KitapPage model)
        {
            if (Session["Uye_adi"] == null)
            {
                return RedirectToAction("Login", "Login");
            }

            int sayfano = model.page ?? 1;
            model.kit = (from a in db.Kitaplar.Where(b =>
                    (String.IsNullOrEmpty(model.KitapAdi) || b.KitapAdi.Contains(model.KitapAdi)) && (String.IsNullOrEmpty(model.YazarAdi) || b.KitapYazari.Contains(model.YazarAdi))

                ).OrderBy(f => f.KitapId)
                         select new KitapPage
                         {

                             KitapAdi = a.KitapAdi,
                             YazarAdi = a.KitapYazari,
                             KitapUrl = a.KitapUrl,
                             Kitapid = a.KitapId

                         }).ToPagedList(sayfano,6);
            if (Request.IsAjaxRequest())
            {
                if (Session["Uye_adi"] == null)
                {
                    return RedirectToAction("Login", "Login");
                }
                return PartialView("_kitapp", model);
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult Kitapicerikleri(string kitapismi)
        {
            if (Session["Uye_adi"] == null)
            {
                return RedirectToAction("Login","Login");
            }
            var sorgu = db.Kitaplar.Where(a => a.KitapAdi == kitapismi).ToList();
            List<Kitaplar> yeni = new List<Kitaplar>();
            foreach (var item in sorgu)
            {
                Kitaplar a = new Kitaplar();
                a.KitapAdi = item.KitapAdi;
                a.KitapId = item.KitapId;
                a.KitapUrl = item.KitapUrl;
                a.KitapYazari = item.KitapYazari;
                a.KitapDurumu = item.KitapDurumu;
                yeni.Add(a);

            }

            return View(yeni);
        }

        public ActionResult KitapListesi()
        {
            var sorgu = db.Kitaplar.ToList();
            List<Kitaplar> yeni = new List<Kitaplar>();
            foreach (var item in sorgu)
            {
                if (Session["Uye_adi"] == null)
                {
                    return RedirectToAction("Login", "Login");
                }
                Kitaplar a = new Kitaplar();
                a.KitapAdi = item.KitapAdi;
                a.KitapId = item.KitapId;
                a.KitapUrl = item.KitapUrl;
                a.KitapYazari = item.KitapYazari;
                a.KitapDurumu = item.KitapDurumu;
                yeni.Add(a);

            }

            return View(yeni);
        }

        public ActionResult KiralamaIslemi()
        {
            
            
            return View();
        }


      

       
    }
}

WebApplication43/Views/Anasayfa/Index.cshtml
@model WebApplication43.Models.KitapPage
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-sm-3">
    <div class="search_box pull-right">
        @using (Ajax.BeginForm("Index", "Anasayfa", FormMethod.Post, new AjaxOptions { OnSuccess = "loadcust" }))
        {

            <h3>Kitap Adi</h3>
            @Html.TextBoxFor(m => m.KitapAdi)

            <h3>Yazar Adi</h3>
            @Html.TextBoxFor(m => m.YazarAdi)
            <br /> <br /> <br />
            <input type="submit" value="ara" name="submit" />

        }
    </div>
</div>

<div id="ajax-main">

    @Html.Partial("_kitapp", @Model)

</div>

WebApplication43/Views/Anasayfa/KiralamaIslemi.cshtml
@{
    ViewBag.Title = "KiralamaIslemi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>KiralamaIslemi</h2>

WebApplication43/Views/Anasayfa/KitapListesi.cshtml
@model List<WebApplication43.Models.Kitaplar>

@{
    ViewBag.Title = "KitapListesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>KitapListesi</h2>

<table class="table">
    <tr>
        <th>
            Kitap Adı
        </th>
        <th>
            Yazar Adı
        </th>
    </tr>

    @foreach (var item in @Model)
    {
        <tr>
            <th>
                @item.KitapAdi
            </th>
            <th>
                @item.KitapYazari
            </th>
        </tr>
    }



</table>

WebApplication43/Views/Anasayfa/Kitapicerikleri.cshtml
@model  List<WebApplication43.Models.Kitaplar>

@{
    ViewBag.Title = "Kitapicerikleri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@foreach (var item in @Model)
{
    <div class="product-details">
        <!--product-details-->
        <div class="col-sm-5">
            <div class="view-product">
                <img src="../../Templatedosyalari/images/home/@item.KitapUrl" />
            </div>

        </div>

        <div class="col-sm-7">
            <div class="product-information">
                <!--/product-information-->
                <h2>@item.KitapAdi</h2>
                <span>                  
                    <i class="fa fa-shopping-cart"> </i>
                    @Html.ActionLink("Kirala", "KiralamaIslemi", "Anasayfa", null, new
                    {
                        @class = "btn btn-fefault cart"
                    })

                    @*<button type="button" class="btn btn-fefault cart">
                            <i class="fa fa-shopping-cart"> </i>

                            Kirala
                        </button*@@*>*@
                </span>
                <p><b>YAZAR:</b>@item.KitapYazari</p>
            </div><!--/product-information-->
        </div>
    </div>

}

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

WebApplication43/Views/Anasayfa/_kitapp.cshtml
@model WebApplication43.Models.KitapPage
@using PagedList
@using PagedList.Mvc
@using WebApplication43.Controllers




<div class="col-sm-9 padding-right">
    <div class="features_items">
        <!--features_items-->
        <h2 class="title text-center">Kitaplar</h2>
        @foreach (var item in Model.kit)
        {
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="../../Templatedosyalari/images/home/@item.KitapUrl" alt="" />                         
                            <p>@item.KitapAdi</p>
                            @Html.ActionLink("KitapDetaylari", "Kitapicerikleri", "Anasayfa", new { kitapismi = item.KitapAdi }, null)

                        </div>

                    </div>

                </div>
            </div>
        }


    </div>
</div>

@Html.PagedListPager(Model.kit, page => Url.Action("Index", new RouteValueDictionary
{
{"page",page},
{"KitapAdi",Model.KitapAdi },
{"YazarAdi",Model.YazarAdi }



}), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions { UpdateTargetId = "ajax-main" }))